import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidePannel from "@/components/SidePannel";
import NavBtn from "@/components/ui/NavBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="h-screen xl:flex">
         <SidePannel/>
         <div className="flex items-center text-white xl:hidden bg-[#193279]">
          <NavBtn type="discussion"/>
          <NavBtn type="market"/>
         </div>

         {children}
      </div>
      </body>
    </html>
  );
}
